FROM ruby:3.3-bullseye

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential git tzdata ca-certificates \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /work
EXPOSE 4000 35729
